# Site settings
title: Jiman's instruction
description: "Jiman's instruction, build with Jekyll."
url: "https://hurjeesic.github.io"
author:
  name: "Hur Jee Sic"
  email: "hurjeesic@naver.com"
  url: "https://hurjeesic.github.io"

# Build settings
baseurl: "/" # Change this to your relative path (ex: /blog/), or leave just a /
markdown: kramdown
source: .
destination: ./_site
permalink: /:title
paginate: 8
paginate_path: /page:num/

# Default values
defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"

# Encoding
encoding: UTF-8

# Plugins
gems:
  - jekyll-paginate

# Custom variables
version: "1.1.0"

# Options
custom_header: false
custom_nav_footer: false
reverse: false
